/* eslint-disable */
/* prettier-ignore */
import type { TadaDocumentNode, $tada } from 'gql.tada';
import type { introspection } from "./graphql-env.d";

declare module 'gql.tada' {
 interface setupCache {
    "\n  query BeanCardFlavorColors {\n    flavorDescriptors {\n      name\n      color\n    }\n  }\n":
      TadaDocumentNode<{ flavorDescriptors: { name: string; color: string; }[]; }, {}, void>;
    "\n  fragment BeanCardFields on Bean @_unmask {\n    id\n    name\n    origin\n    process\n    suggestedFlavors\n  }\n":
      TadaDocumentNode<{ id: string; name: string; origin: string | null; process: string | null; suggestedFlavors: string[]; }, {}, { fragment: "BeanCardFields"; on: "Bean"; masked: false; }>;
    "\n  fragment FlavorDescriptorFields on FlavorDescriptor @_unmask {\n    id\n    name\n    category\n    color\n    isOffFlavor\n  }\n":
      TadaDocumentNode<{ id: string; name: string; category: "FRUITY" | "SOUR_FERMENTED" | "GREEN_VEGETATIVE" | "OTHER" | "ROASTED" | "SPICES" | "NUTTY_COCOA" | "SWEET" | "FLORAL" | "OFF_FLAVOR"; color: string; isOffFlavor: boolean; }, {}, { fragment: "FlavorDescriptorFields"; on: "FlavorDescriptor"; masked: false; }>;
    "\n  fragment RoastRowFields on Roast @_unmask {\n    id\n    roastDate\n    rating\n    totalDuration\n    firstCrackTemp\n    developmentPercent\n    bean { id name }\n  }\n":
      TadaDocumentNode<{ id: string; roastDate: string | null; rating: number | null; totalDuration: number | null; firstCrackTemp: number | null; developmentPercent: number | null; bean: { id: string; name: string; }; }, {}, { fragment: "RoastRowFields"; on: "Roast"; masked: false; }>;
    "\n  fragment RoastMetricFields on Roast @_unmask {\n    id\n    roastDate\n    totalDuration\n    colourChangeTime\n    colourChangeTemp\n    firstCrackTime\n    firstCrackTemp\n    developmentTime\n    developmentPercent\n    roastEndTemp\n  }\n":
      TadaDocumentNode<{ id: string; roastDate: string | null; totalDuration: number | null; colourChangeTime: number | null; colourChangeTemp: number | null; firstCrackTime: number | null; firstCrackTemp: number | null; developmentTime: number | null; developmentPercent: number | null; roastEndTemp: number | null; }, {}, { fragment: "RoastMetricFields"; on: "Roast"; masked: false; }>;
    "\n  query MyRoasts {\n    myRoasts {\n      ...RoastRowFields\n      notes\n      developmentTime\n      roastEndTemp\n      colourChangeTime\n      colourChangeTemp\n      firstCrackTime\n      roastEndTime\n      isPublic\n      flavors { ...FlavorDescriptorFields }\n      offFlavors { ...FlavorDescriptorFields }\n    }\n  }\n":
      TadaDocumentNode<{ myRoasts: { id: string; roastDate: string | null; rating: number | null; totalDuration: number | null; firstCrackTemp: number | null; developmentPercent: number | null; bean: { id: string; name: string; }; notes: string | null; developmentTime: number | null; roastEndTemp: number | null; colourChangeTime: number | null; colourChangeTemp: number | null; firstCrackTime: number | null; roastEndTime: number | null; isPublic: boolean; flavors: { id: string; name: string; category: "FRUITY" | "SOUR_FERMENTED" | "GREEN_VEGETATIVE" | "OTHER" | "ROASTED" | "SPICES" | "NUTTY_COCOA" | "SWEET" | "FLORAL" | "OFF_FLAVOR"; color: string; isOffFlavor: boolean; }[]; offFlavors: { id: string; name: string; category: "FRUITY" | "SOUR_FERMENTED" | "GREEN_VEGETATIVE" | "OTHER" | "ROASTED" | "SPICES" | "NUTTY_COCOA" | "SWEET" | "FLORAL" | "OFF_FLAVOR"; color: string; isOffFlavor: boolean; }[]; }[]; }, {}, void>;
    "\n  query MyBeans {\n    myBeans {\n      id\n      shortName\n      notes\n      bean {\n        ...BeanCardFields\n        elevation\n        variety\n        sourceUrl\n        bagNotes\n        score\n        cropYear\n      }\n    }\n  }\n":
      TadaDocumentNode<{ myBeans: { id: string; shortName: string | null; notes: string | null; bean: { id: string; name: string; origin: string | null; process: string | null; suggestedFlavors: string[]; elevation: string | null; variety: string | null; sourceUrl: string | null; bagNotes: string | null; score: number | null; cropYear: number | null; }; }[]; }, {}, void>;
    "\n  query RoastById($id: String!) {\n    roastById(id: $id) {\n      ...RoastRowFields\n      ...RoastMetricFields\n      notes\n      ambientTemp\n      roastEndTime\n      timeSeriesData\n      roastProfileCurve\n      fanProfileCurve\n      isPublic\n      userId\n      bean { origin process elevation variety sourceUrl }\n      roastProfile { id fileName }\n      flavors { ...FlavorDescriptorFields }\n      offFlavors { ...FlavorDescriptorFields }\n    }\n  }\n":
      TadaDocumentNode<{ roastById: { id: string; roastDate: string | null; rating: number | null; totalDuration: number | null; firstCrackTemp: number | null; developmentPercent: number | null; bean: { id: string; name: string; } & { origin: string | null; process: string | null; elevation: string | null; variety: string | null; sourceUrl: string | null; }; colourChangeTime: number | null; colourChangeTemp: number | null; firstCrackTime: number | null; developmentTime: number | null; roastEndTemp: number | null; notes: string | null; ambientTemp: number | null; roastEndTime: number | null; timeSeriesData: unknown; roastProfileCurve: unknown; fanProfileCurve: unknown; isPublic: boolean; userId: string; roastProfile: { id: string; fileName: string; } | null; flavors: { id: string; name: string; category: "FRUITY" | "SOUR_FERMENTED" | "GREEN_VEGETATIVE" | "OTHER" | "ROASTED" | "SPICES" | "NUTTY_COCOA" | "SWEET" | "FLORAL" | "OFF_FLAVOR"; color: string; isOffFlavor: boolean; }[]; offFlavors: { id: string; name: string; category: "FRUITY" | "SOUR_FERMENTED" | "GREEN_VEGETATIVE" | "OTHER" | "ROASTED" | "SPICES" | "NUTTY_COCOA" | "SWEET" | "FLORAL" | "OFF_FLAVOR"; color: string; isOffFlavor: boolean; }[]; } | null; }, { id: string; }, void>;
    "\n  query RoastsByBean($beanId: String!) {\n    roastsByBean(beanId: $beanId) {\n      ...RoastRowFields\n      ...RoastMetricFields\n      notes\n      flavors { ...FlavorDescriptorFields }\n      offFlavors { ...FlavorDescriptorFields }\n    }\n  }\n":
      TadaDocumentNode<{ roastsByBean: { id: string; roastDate: string | null; rating: number | null; totalDuration: number | null; firstCrackTemp: number | null; developmentPercent: number | null; bean: { id: string; name: string; }; colourChangeTime: number | null; colourChangeTemp: number | null; firstCrackTime: number | null; developmentTime: number | null; roastEndTemp: number | null; notes: string | null; flavors: { id: string; name: string; category: "FRUITY" | "SOUR_FERMENTED" | "GREEN_VEGETATIVE" | "OTHER" | "ROASTED" | "SPICES" | "NUTTY_COCOA" | "SWEET" | "FLORAL" | "OFF_FLAVOR"; color: string; isOffFlavor: boolean; }[]; offFlavors: { id: string; name: string; category: "FRUITY" | "SOUR_FERMENTED" | "GREEN_VEGETATIVE" | "OTHER" | "ROASTED" | "SPICES" | "NUTTY_COCOA" | "SWEET" | "FLORAL" | "OFF_FLAVOR"; color: string; isOffFlavor: boolean; }[]; }[]; }, { beanId: string; }, void>;
    "\n  query RoastsByIds($ids: [String!]!) {\n    roastsByIds(ids: $ids) {\n      ...RoastRowFields\n      ...RoastMetricFields\n      roastEndTime\n      timeSeriesData\n    }\n  }\n":
      TadaDocumentNode<{ roastsByIds: { id: string; roastDate: string | null; rating: number | null; totalDuration: number | null; firstCrackTemp: number | null; developmentPercent: number | null; bean: { id: string; name: string; }; colourChangeTime: number | null; colourChangeTemp: number | null; firstCrackTime: number | null; developmentTime: number | null; roastEndTemp: number | null; roastEndTime: number | null; timeSeriesData: unknown; }[]; }, { ids: string[]; }, void>;
    "\n  query PublicRoast($id: String!) {\n    roast(id: $id) {\n      ...RoastRowFields\n      ...RoastMetricFields\n      notes\n      ambientTemp\n      roastEndTime\n      timeSeriesData\n      roastProfileCurve\n      fanProfileCurve\n      isPublic\n      userId\n      bean { origin process elevation variety sourceUrl }\n      roastProfile { id fileName }\n      flavors { ...FlavorDescriptorFields }\n      offFlavors { ...FlavorDescriptorFields }\n    }\n  }\n":
      TadaDocumentNode<{ roast: { id: string; roastDate: string | null; rating: number | null; totalDuration: number | null; firstCrackTemp: number | null; developmentPercent: number | null; bean: { id: string; name: string; } & { origin: string | null; process: string | null; elevation: string | null; variety: string | null; sourceUrl: string | null; }; colourChangeTime: number | null; colourChangeTemp: number | null; firstCrackTime: number | null; developmentTime: number | null; roastEndTemp: number | null; notes: string | null; ambientTemp: number | null; roastEndTime: number | null; timeSeriesData: unknown; roastProfileCurve: unknown; fanProfileCurve: unknown; isPublic: boolean; userId: string; roastProfile: { id: string; fileName: string; } | null; flavors: { id: string; name: string; category: "FRUITY" | "SOUR_FERMENTED" | "GREEN_VEGETATIVE" | "OTHER" | "ROASTED" | "SPICES" | "NUTTY_COCOA" | "SWEET" | "FLORAL" | "OFF_FLAVOR"; color: string; isOffFlavor: boolean; }[]; offFlavors: { id: string; name: string; category: "FRUITY" | "SOUR_FERMENTED" | "GREEN_VEGETATIVE" | "OTHER" | "ROASTED" | "SPICES" | "NUTTY_COCOA" | "SWEET" | "FLORAL" | "OFF_FLAVOR"; color: string; isOffFlavor: boolean; }[]; } | null; }, { id: string; }, void>;
    "\n  query PublicBeans($limit: Int) {\n    publicBeans(limit: $limit) {\n      ...BeanCardFields\n      variety\n    }\n  }\n":
      TadaDocumentNode<{ publicBeans: { id: string; name: string; origin: string | null; process: string | null; suggestedFlavors: string[]; variety: string | null; }[]; }, { limit?: number | null | undefined; }, void>;
    "\n  query PublicRoasts($beanId: String, $limit: Int, $offset: Int) {\n    publicRoasts(beanId: $beanId, limit: $limit, offset: $offset) {\n      ...RoastRowFields\n      developmentTime\n      roastEndTemp\n    }\n  }\n":
      TadaDocumentNode<{ publicRoasts: { id: string; roastDate: string | null; rating: number | null; totalDuration: number | null; firstCrackTemp: number | null; developmentPercent: number | null; bean: { id: string; name: string; }; developmentTime: number | null; roastEndTemp: number | null; }[]; }, { offset?: number | null | undefined; limit?: number | null | undefined; beanId?: string | null | undefined; }, void>;
    "\n  query PublicBean($id: String!) {\n    bean(id: $id) {\n      id\n      name\n      origin\n      process\n      elevation\n      variety\n      sourceUrl\n      bagNotes\n      score\n      cropYear\n      suggestedFlavors\n    }\n  }\n":
      TadaDocumentNode<{ bean: { id: string; name: string; origin: string | null; process: string | null; elevation: string | null; variety: string | null; sourceUrl: string | null; bagNotes: string | null; score: number | null; cropYear: number | null; suggestedFlavors: string[]; } | null; }, { id: string; }, void>;
    "\n  query CommunityStats {\n    communityStats {\n      totalRoasts\n      totalBeans\n    }\n  }\n":
      TadaDocumentNode<{ communityStats: { totalRoasts: number; totalBeans: number; }; }, {}, void>;
    "\n  query PreviewRoastLog($fileName: String!, $fileContent: String!) {\n    previewRoastLog(fileName: $fileName, fileContent: $fileContent) {\n      roastDate\n      ambientTemp\n      roastingLevel\n      profileShortName\n      profileDesigner\n      colourChangeTime\n      firstCrackTime\n      roastEndTime\n      developmentPercent\n      totalDuration\n      suggestedBeans {\n        id\n        shortName\n        bean { id name }\n      }\n      communityBeans {\n        id\n        name\n      }\n      parseWarnings\n      existingRoastId\n    }\n  }\n":
      TadaDocumentNode<{ previewRoastLog: { roastDate: string | null; ambientTemp: number | null; roastingLevel: number | null; profileShortName: string | null; profileDesigner: string | null; colourChangeTime: number | null; firstCrackTime: number | null; roastEndTime: number | null; developmentPercent: number | null; totalDuration: number | null; suggestedBeans: { id: string; shortName: string | null; bean: { id: string; name: string; }; }[]; communityBeans: { id: string; name: string; }[]; parseWarnings: string[]; existingRoastId: string | null; }; }, { fileContent: string; fileName: string; }, void>;
    "\n  query PreviewRoastLogs($files: [RoastLogInput!]!) {\n    previewRoastLogs(files: $files) {\n      fileName\n      error\n      preview {\n        roastDate\n        ambientTemp\n        roastingLevel\n        profileShortName\n        profileDesigner\n        colourChangeTime\n        firstCrackTime\n        roastEndTime\n        developmentPercent\n        totalDuration\n        suggestedBeans {\n          id\n          shortName\n          bean { id name }\n        }\n        communityBeans {\n          id\n          name\n        }\n        parseWarnings\n        existingRoastId\n      }\n    }\n  }\n":
      TadaDocumentNode<{ previewRoastLogs: { fileName: string; error: string | null; preview: { roastDate: string | null; ambientTemp: number | null; roastingLevel: number | null; profileShortName: string | null; profileDesigner: string | null; colourChangeTime: number | null; firstCrackTime: number | null; roastEndTime: number | null; developmentPercent: number | null; totalDuration: number | null; suggestedBeans: { id: string; shortName: string | null; bean: { id: string; name: string; }; }[]; communityBeans: { id: string; name: string; }[]; parseWarnings: string[]; existingRoastId: string | null; } | null; }[]; }, { files: { fileContent: string; fileName: string; }[]; }, void>;
    "\n  query FlavorDescriptors($isOffFlavor: Boolean) {\n    flavorDescriptors(isOffFlavor: $isOffFlavor) {\n      ...FlavorDescriptorFields\n      isCustom\n    }\n  }\n":
      TadaDocumentNode<{ flavorDescriptors: { id: string; name: string; category: "FRUITY" | "SOUR_FERMENTED" | "GREEN_VEGETATIVE" | "OTHER" | "ROASTED" | "SPICES" | "NUTTY_COCOA" | "SWEET" | "FLORAL" | "OFF_FLAVOR"; color: string; isOffFlavor: boolean; isCustom: boolean; }[]; }, { isOffFlavor?: boolean | null | undefined; }, void>;
    "\n  query ParseSupplierNotes($text: String!) {\n    parseSupplierNotes(text: $text) {\n      id\n      name\n      category\n      color\n    }\n  }\n":
      TadaDocumentNode<{ parseSupplierNotes: { id: string; name: string; category: "FRUITY" | "SOUR_FERMENTED" | "GREEN_VEGETATIVE" | "OTHER" | "ROASTED" | "SPICES" | "NUTTY_COCOA" | "SWEET" | "FLORAL" | "OFF_FLAVOR"; color: string; }[]; }, { text: string; }, void>;
    "\n  query UserSettings {\n    userSettings {\n      id\n      tempUnit\n      theme\n      privateByDefault\n    }\n  }\n":
      TadaDocumentNode<{ userSettings: { id: string; tempUnit: "CELSIUS" | "FAHRENHEIT"; theme: string; privateByDefault: boolean; }; }, {}, void>;
    "\n  query ScrapeBeanUrl($url: String!) {\n    scrapeBeanUrl(url: $url) {\n      name\n      origin\n      process\n      elevation\n      variety\n      bagNotes\n      score\n      cropYear\n      suggestedFlavors\n    }\n  }\n":
      TadaDocumentNode<{ scrapeBeanUrl: { name: string | null; origin: string | null; process: string | null; elevation: string | null; variety: string | null; bagNotes: string | null; score: number | null; cropYear: number | null; suggestedFlavors: string[] | null; }; }, { url: string; }, void>;
    "\n  query ParseBeanPage($html: String!) {\n    parseBeanPage(html: $html) {\n      name\n      origin\n      process\n      elevation\n      variety\n      bagNotes\n      score\n      cropYear\n      suggestedFlavors\n    }\n  }\n":
      TadaDocumentNode<{ parseBeanPage: { name: string | null; origin: string | null; process: string | null; elevation: string | null; variety: string | null; bagNotes: string | null; score: number | null; cropYear: number | null; suggestedFlavors: string[] | null; }; }, { html: string; }, void>;
    "\n  query DownloadProfile($roastId: String!) {\n    downloadProfile(roastId: $roastId) {\n      fileName\n      content\n    }\n  }\n":
      TadaDocumentNode<{ downloadProfile: { fileName: string; content: string; } | null; }, { roastId: string; }, void>;
    "\n  query DistinctSuppliers {\n    distinctSuppliers\n  }\n":
      TadaDocumentNode<{ distinctSuppliers: string[]; }, {}, void>;
    "\n  mutation UploadRoastLog($beanId: String!, $fileName: String!, $fileContent: String!, $notes: String) {\n    uploadRoastLog(beanId: $beanId, fileName: $fileName, fileContent: $fileContent, notes: $notes) {\n      roast { id }\n      parseWarnings\n      wasDuplicate\n    }\n  }\n":
      TadaDocumentNode<{ uploadRoastLog: { roast: { id: string; }; parseWarnings: string[]; wasDuplicate: boolean; }; }, { notes?: string | null | undefined; fileContent: string; fileName: string; beanId: string; }, void>;
    "\n  mutation UpdateRoastRating($id: String!, $input: UpdateRoastInput!) {\n    updateRoast(id: $id, input: $input) {\n      id\n      rating\n    }\n  }\n":
      TadaDocumentNode<{ updateRoast: { id: string; rating: number | null; }; }, { input: { rating?: number | null | undefined; notes?: string | null | undefined; fanProfileCurve?: unknown; roastProfileCurve?: unknown; timeSeriesData?: unknown; roastDate?: string | null | undefined; totalDuration?: number | null | undefined; developmentPercent?: number | null | undefined; developmentTime?: number | null | undefined; roastEndTemp?: number | null | undefined; firstCrackTemp?: number | null | undefined; colourChangeTemp?: number | null | undefined; roastEndTime?: number | null | undefined; firstCrackTime?: number | null | undefined; colourChangeTime?: number | null | undefined; tastingNotes?: string | null | undefined; roastingLevel?: number | null | undefined; ambientTemp?: number | null | undefined; }; id: string; }, void>;
    "\n  mutation UpdateRoast($id: String!, $input: UpdateRoastInput!) {\n    updateRoast(id: $id, input: $input) {\n      id\n      notes\n      rating\n    }\n  }\n":
      TadaDocumentNode<{ updateRoast: { id: string; notes: string | null; rating: number | null; }; }, { input: { rating?: number | null | undefined; notes?: string | null | undefined; fanProfileCurve?: unknown; roastProfileCurve?: unknown; timeSeriesData?: unknown; roastDate?: string | null | undefined; totalDuration?: number | null | undefined; developmentPercent?: number | null | undefined; developmentTime?: number | null | undefined; roastEndTemp?: number | null | undefined; firstCrackTemp?: number | null | undefined; colourChangeTemp?: number | null | undefined; roastEndTime?: number | null | undefined; firstCrackTime?: number | null | undefined; colourChangeTime?: number | null | undefined; tastingNotes?: string | null | undefined; roastingLevel?: number | null | undefined; ambientTemp?: number | null | undefined; }; id: string; }, void>;
    "\n  mutation DeleteRoast($id: String!) {\n    deleteRoast(id: $id)\n  }\n":
      TadaDocumentNode<{ deleteRoast: boolean; }, { id: string; }, void>;
    "\n  mutation RemoveBeanFromLibrary($beanId: String!) {\n    removeBeanFromLibrary(beanId: $beanId)\n  }\n":
      TadaDocumentNode<{ removeBeanFromLibrary: boolean; }, { beanId: string; }, void>;
    "\n  mutation ToggleRoastPublic($id: String!) {\n    toggleRoastPublic(id: $id) {\n      id\n      isPublic\n    }\n  }\n":
      TadaDocumentNode<{ toggleRoastPublic: { id: string; isPublic: boolean; }; }, { id: string; }, void>;
    "\n  mutation UpdateTheme($theme: String!) {\n    updateTheme(theme: $theme) {\n      id\n      theme\n    }\n  }\n":
      TadaDocumentNode<{ updateTheme: { id: string; theme: string; }; }, { theme: string; }, void>;
    "\n  mutation UpdatePrivacyDefault($privateByDefault: Boolean!) {\n    updatePrivacyDefault(privateByDefault: $privateByDefault) {\n      id\n      privateByDefault\n    }\n  }\n":
      TadaDocumentNode<{ updatePrivacyDefault: { id: string; privateByDefault: boolean; }; }, { privateByDefault: boolean; }, void>;
    "\n  mutation SetRoastFlavors($roastId: String!, $descriptorIds: [String!]!) {\n    setRoastFlavors(roastId: $roastId, descriptorIds: $descriptorIds) {\n      id\n      flavors { ...FlavorDescriptorFields }\n    }\n  }\n":
      TadaDocumentNode<{ setRoastFlavors: { id: string; flavors: { id: string; name: string; category: "FRUITY" | "SOUR_FERMENTED" | "GREEN_VEGETATIVE" | "OTHER" | "ROASTED" | "SPICES" | "NUTTY_COCOA" | "SWEET" | "FLORAL" | "OFF_FLAVOR"; color: string; isOffFlavor: boolean; }[]; }; }, { descriptorIds: string[]; roastId: string; }, void>;
    "\n  mutation SetRoastOffFlavors($roastId: String!, $descriptorIds: [String!]!) {\n    setRoastOffFlavors(roastId: $roastId, descriptorIds: $descriptorIds) {\n      id\n      offFlavors { ...FlavorDescriptorFields }\n    }\n  }\n":
      TadaDocumentNode<{ setRoastOffFlavors: { id: string; offFlavors: { id: string; name: string; category: "FRUITY" | "SOUR_FERMENTED" | "GREEN_VEGETATIVE" | "OTHER" | "ROASTED" | "SPICES" | "NUTTY_COCOA" | "SWEET" | "FLORAL" | "OFF_FLAVOR"; color: string; isOffFlavor: boolean; }[]; }; }, { descriptorIds: string[]; roastId: string; }, void>;
    "\n  mutation CreateBean($input: CreateBeanInput!) {\n    createBean(input: $input) {\n      id\n      shortName\n      bean { id name origin process elevation variety sourceUrl bagNotes supplier score cropYear suggestedFlavors }\n    }\n  }\n":
      TadaDocumentNode<{ createBean: { id: string; shortName: string | null; bean: { id: string; name: string; origin: string | null; process: string | null; elevation: string | null; variety: string | null; sourceUrl: string | null; bagNotes: string | null; supplier: string | null; score: number | null; cropYear: number | null; suggestedFlavors: string[]; }; }; }, { input: { suggestedFlavors?: string[] | null | undefined; shortName?: string | null | undefined; notes?: string | null | undefined; score?: number | null | undefined; supplier?: string | null | undefined; bagNotes?: string | null | undefined; variety?: string | null | undefined; elevation?: string | null | undefined; sourceUrl?: string | null | undefined; cropYear?: number | null | undefined; process?: string | null | undefined; origin?: string | null | undefined; name: string; }; }, void>;
    "\n  mutation UpdateBean($id: String!, $input: UpdateBeanInput!) {\n    updateBean(id: $id, input: $input) {\n      id\n      name\n      origin\n      process\n      elevation\n      variety\n      bagNotes\n      score\n      cropYear\n    }\n  }\n":
      TadaDocumentNode<{ updateBean: { id: string; name: string; origin: string | null; process: string | null; elevation: string | null; variety: string | null; bagNotes: string | null; score: number | null; cropYear: number | null; }; }, { input: { score?: number | null | undefined; supplier?: string | null | undefined; bagNotes?: string | null | undefined; elevation?: string | null | undefined; sourceUrl?: string | null | undefined; cropYear?: number | null | undefined; }; id: string; }, void>;
    "\n  mutation UpdateUserBean($id: String!, $notes: String, $shortName: String) {\n    updateUserBean(id: $id, notes: $notes, shortName: $shortName) {\n      id\n      notes\n      shortName\n    }\n  }\n":
      TadaDocumentNode<{ updateUserBean: { id: string; notes: string | null; shortName: string | null; }; }, { shortName?: string | null | undefined; notes?: string | null | undefined; id: string; }, void>;
    "\n  mutation UpdateBeanSuggestedFlavors($beanId: String!, $suggestedFlavors: [String!]!) {\n    updateBeanSuggestedFlavors(beanId: $beanId, suggestedFlavors: $suggestedFlavors) {\n      id\n      suggestedFlavors\n    }\n  }\n":
      TadaDocumentNode<{ updateBeanSuggestedFlavors: { id: string; suggestedFlavors: string[]; }; }, { suggestedFlavors: string[]; beanId: string; }, void>;
    "\n  mutation CreateFlavorDescriptor($name: String!, $category: FlavorCategory!) {\n    createFlavorDescriptor(name: $name, category: $category) {\n      ...FlavorDescriptorFields\n      isCustom\n    }\n  }\n":
      TadaDocumentNode<{ createFlavorDescriptor: { id: string; name: string; category: "FRUITY" | "SOUR_FERMENTED" | "GREEN_VEGETATIVE" | "OTHER" | "ROASTED" | "SPICES" | "NUTTY_COCOA" | "SWEET" | "FLORAL" | "OFF_FLAVOR"; color: string; isOffFlavor: boolean; isCustom: boolean; }; }, { category: "FRUITY" | "SOUR_FERMENTED" | "GREEN_VEGETATIVE" | "OTHER" | "ROASTED" | "SPICES" | "NUTTY_COCOA" | "SWEET" | "FLORAL" | "OFF_FLAVOR"; name: string; }, void>;
    "\n  mutation UpdateTempUnit($tempUnit: TempUnit!) {\n    updateTempUnit(tempUnit: $tempUnit) {\n      id\n      tempUnit\n    }\n  }\n":
      TadaDocumentNode<{ updateTempUnit: { id: string; tempUnit: "CELSIUS" | "FAHRENHEIT"; }; }, { tempUnit: "CELSIUS" | "FAHRENHEIT"; }, void>;
    "\n  fragment MetricsFields on Roast @_unmask {\n    totalDuration\n    colourChangeTime\n    colourChangeTemp\n    firstCrackTime\n    firstCrackTemp\n    developmentTime\n    developmentPercent\n    roastEndTemp\n    rating\n  }\n":
      TadaDocumentNode<{ totalDuration: number | null; colourChangeTime: number | null; colourChangeTemp: number | null; firstCrackTime: number | null; firstCrackTemp: number | null; developmentTime: number | null; developmentPercent: number | null; roastEndTemp: number | null; rating: number | null; }, {}, { fragment: "MetricsFields"; on: "Roast"; masked: false; }>;
  }
}
